version: '2'
services:
  mysqldb:
    image: mysql:5.5
    container_name: mysqldb
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=root1234
      - MYSQL_DATABASE=spring_app_db
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=Admin@1234
      - MYSQL_ROOT_HOST=localhost
    volumes:
      - /data/mysql
  mongodb:
    image: mongo:2.4
    container_name: mongodb
    ports:
     - "27017:27017"
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
     - "5672:5672"
     - "15672:15672"
    environment:
     - RABBITMQ_DEFAULT_USER=test
     - RABBITMQ_DEFAULT_PASS=password
  config:
    image: jemsotry/config-service
    container_name: config
    ports:
     - "8888:8888"
    environment:
     - SPRING_PROFILES_ACTIVE=production
    depends_on:
     - mongodb
     - rabbitmq
  discovery:
    image: jemsotry/discovery-service
    container_name: discovery
    ports:
     - "8761:8761"
  gateway:
    image: jemsotry/gateway-service
    container_name: gateway
    ports:
     - "8181:8181"
    environment:
     - SPRING_PROFILES_ACTIVE=production
    depends_on:
     - discovery
     - config
  product-command-side:
    image: jemsotry/product-command-side:latest
    container_name: product-cmd-side
    depends_on:
     - mongodb
     - rabbitmq
     - discovery
     - config
    ports:
      - "9000"
    environment:
     - SPRING_PROFILES_ACTIVE=production
  product-query-side:
    image: jemsotry/product-query-side:latest
    container_name: product-qry-side
    depends_on:
     - mysqldb
     - rabbitmq
     - discovery
     - config
    ports:
     - "9001"
    volumes:
     - /data/spring-boot-app
    environment:
     - SPRING_PROFILES_ACTIVE=production
